import 'dart:io';
import 'package:path/path.dart' as p;
import '../models/site_model.dart';
import 'config_service.dart';
import 'ssl_service.dart';

class VhostConfigGenerator {
  static final VhostConfigGenerator instance = VhostConfigGenerator._();
  VhostConfigGenerator._();

  static List<int> getFastCgiPorts(String? versionKey) {
    final norm = ConfigService.normalizePhpVersionKey(versionKey);
    switch (norm) {
      case '7.4':
        return const [9074, 9174, 9274, 9374];
      case '8.1':
        return const [9081, 9181, 9281, 9381];
      case '8.2':
        return const [9082, 9182, 9282, 9382];
      case '8.3':
        return const [9083, 9183, 9283, 9383];
      case 'default':
      default:
        return const [9000, 9001, 9002, 9003];
    }
  }

  static int getFastCgiPort(String? versionKey) {
    return getFastCgiPorts(versionKey).first;
  }

  static String getUpstreamName(String? versionKey) {
    final norm = ConfigService.normalizePhpVersionKey(versionKey);
    if (norm == 'default' || norm.isEmpty) return 'php_default_pool';
    return 'php_${norm.replaceAll('.', '_')}_pool';
  }

  String _toForwardSlash(String path) {
    return p.normalize(path).replaceAll(r'\', '/');
  }

  String _getEffectiveDocRoot(String rootPath) {
    final publicHtmlFolder = p.join(rootPath, 'public_html');
    final publicFolder = p.join(rootPath, 'public');
    if (!File(p.join(rootPath, 'index.php')).existsSync() &&
        (File(p.join(publicHtmlFolder, 'index.php')).existsSync() ||
         File(p.join(publicHtmlFolder, 'index.html')).existsSync())) {
      return _toForwardSlash(publicHtmlFolder);
    }
    if (Directory(publicFolder).existsSync()) {
      return _toForwardSlash(publicFolder);
    }
    return _toForwardSlash(rootPath);
  }

  /// Generate complete Nginx main configuration and individual vhost files
  Future<void> generateNginxConfigs(List<SiteModel> sites) async {
    final config = ConfigService.instance;
    final confDir = Directory(config.nginxConfDir);
    final vhostsDir = Directory(config.nginxVhostsDir);

    if (!confDir.existsSync()) confDir.createSync(recursive: true);
    if (!vhostsDir.existsSync()) vhostsDir.createSync(recursive: true);

    final ssl = SslService.instance;
    await ssl.ensureCertificate(sites: sites);
    final hasSsl = ssl.hasCertificate;
    final sslCert = _toForwardSlash(ssl.certPath);
    final sslKey = _toForwardSlash(ssl.keyPath);

    // 1. Ensure mime.types and fastcgi_params exist
    _ensureNginxHelperFiles(config.nginxConfDir);

    // 2. Generate Main nginx.conf
    final demoRoot = _toForwardSlash(config.demoSiteDir);
    final pmaDir = _toForwardSlash(config.phpMyAdminDir);

    final mainNginxConf = '''
# Auto-generated by Devlika Stack Portable
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
    keepalive_timeout  65;
    client_max_body_size 512M;

    # GZIP Compression for ultra-fast transfers
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 5;
    gzip_min_length 256;
    gzip_types
        text/plain
        text/css
        text/xml
        text/javascript
        application/json
        application/javascript
        application/x-javascript
        application/xml
        application/rss+xml
        image/svg+xml;

    # PHP FastCGI Multi-Worker Pools (Zero-queue parallel concurrency for Windows)
    upstream php_default_pool {
        server 127.0.0.1:9000;
        server 127.0.0.1:9001;
        server 127.0.0.1:9002;
        server 127.0.0.1:9003;
        keepalive 32;
    }

    upstream php_7_4_pool {
        server 127.0.0.1:9074;
        server 127.0.0.1:9174;
        server 127.0.0.1:9274;
        server 127.0.0.1:9374;
        keepalive 32;
    }

    upstream php_8_1_pool {
        server 127.0.0.1:9081;
        server 127.0.0.1:9181;
        server 127.0.0.1:9281;
        server 127.0.0.1:9381;
        keepalive 32;
    }

    upstream php_8_2_pool {
        server 127.0.0.1:9082;
        server 127.0.0.1:9182;
        server 127.0.0.1:9282;
        server 127.0.0.1:9382;
        keepalive 32;
    }

    upstream php_8_3_pool {
        server 127.0.0.1:9083;
        server 127.0.0.1:9183;
        server 127.0.0.1:9283;
        server 127.0.0.1:9383;
        keepalive 32;
    }

    # Default localhost / 127.0.0.1 server
    server {
        listen       80 default_server;
        server_name  localhost 127.0.0.1;
        root         "$demoRoot";
        index        index.php index.html index.htm;

        location / {
            try_files \$uri \$uri/ /index.php?\$query_string;
        }

        # phpMyAdmin Alias Route
        location /__phpmyadmin {
            alias "$pmaDir/";
            index index.php;

            location ~ \\.php\$ {
                fastcgi_pass   php_default_pool;
                fastcgi_keep_conn on;
                fastcgi_index  index.php;
                fastcgi_param  SCRIPT_FILENAME  \$request_filename;
                include        fastcgi_params;
                fastcgi_read_timeout 3600;
                fastcgi_buffers 16 16k;
                fastcgi_buffer_size 32k;
            }
        }

        location ~ \\.php\$ {
            fastcgi_pass   php_default_pool;
            fastcgi_keep_conn on;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  \$document_root\$fastcgi_script_name;
            include        fastcgi_params;
            fastcgi_read_timeout 3600;
            fastcgi_buffers 16 16k;
            fastcgi_buffer_size 32k;
        }

        location ~ /\\.(env|git|log|htaccess) {
            deny all;
        }
    }

    # Include all virtual hosts generated by Devlika Stack
    include vhosts/*.conf;
}
''';

    File(config.nginxConfFile).writeAsStringSync(mainNginxConf);

    // 3. Clean and recreate vhosts directory
    if (vhostsDir.existsSync()) {
      for (var f in vhostsDir.listSync()) {
        if (f is File && f.path.endsWith('.conf')) {
          try {
            f.deleteSync();
          } catch (_) {}
        }
      }
    }

    // 4. Generate individual vhost files for enabled sites
    for (var site in sites) {
      if (!site.isEnabled) continue;

      final cleanDomain = site.domain.trim().toLowerCase();
      if (cleanDomain.isEmpty) continue;
      final safeFileName = cleanDomain.replaceAll(RegExp(r'[^a-z0-9_\-\.]'), '_');

      String content;
      if (site.type == 'proxy') {
        content = '''
# Devlika Stack Virtual Host: ${site.domain} (Reverse Proxy)
server {
    listen 80;
    ${hasSsl ? '''listen 443 ssl;
    ssl_certificate "$sslCert";
    ssl_certificate_key "$sslKey";
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;''' : ''}
    server_name ${site.domain};

    location / {
        proxy_pass http://127.0.0.1:${site.proxyPort};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_cache_bypass \$http_upgrade;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
''';
      } else {
        final docRoot = _getEffectiveDocRoot(site.rootPath);
        final upstreamName = getUpstreamName(site.phpVersion);
        content = '''
# Devlika Stack Virtual Host: ${site.domain} (PHP ${site.phpVersion} / Static)
server {
    listen 80;
    ${hasSsl ? '''listen 443 ssl;
    ssl_certificate "$sslCert";
    ssl_certificate_key "$sslKey";
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;''' : ''}
    server_name ${site.domain};
    root "$docRoot";
    index index.php index.html index.htm;

    client_max_body_size 512M;

    # URL Rewriting for Laravel, WordPress, CodeIgniter, SPA
    location / {
        try_files \$uri \$uri/ /index.php?\$query_string;
    }

    location ~ \\.php\$ {
        fastcgi_pass   $upstreamName;
        fastcgi_keep_conn on;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME  \$document_root\$fastcgi_script_name;
        include        fastcgi_params;
        fastcgi_read_timeout 3600;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
    }

    # High-speed static caching (Flash delivery)
    location ~* \\.(jpg|jpeg|png|gif|ico|css|js|woff2|woff|ttf|svg|webp|mp4|webm)\$ {
        expires 7d;
        add_header Cache-Control "public, no-transform";
        access_log off;
    }

    location ~ /\\.(env|git|log|htaccess) {
        deny all;
    }
}
''';
      }

      final vhostFile = File(p.join(config.nginxVhostsDir, '$safeFileName.conf'));
      vhostFile.writeAsStringSync(content);
    }
  }

  /// Generate Apache HTTPD virtual host configuration
  Future<void> generateApacheConfigs(List<SiteModel> sites) async {
    final config = ConfigService.instance;
    final extraDir = Directory(p.join(config.apacheConfDir, 'extra'));
    if (!extraDir.existsSync()) extraDir.createSync(recursive: true);

    final demoRoot = _toForwardSlash(config.demoSiteDir);
    final pmaDir = _toForwardSlash(config.phpMyAdminDir);

    final buffer = StringBuffer();
    buffer.writeln('# Auto-generated by Devlika Stack Portable');
    buffer.writeln('# Default Localhost VirtualHost');
    buffer.writeln('<VirtualHost *:80>');
    buffer.writeln('    ServerName localhost');
    buffer.writeln('    ServerAlias 127.0.0.1');
    buffer.writeln('    DocumentRoot "$demoRoot"');
    buffer.writeln('    <Directory "$demoRoot">');
    buffer.writeln('        Options Indexes FollowSymLinks');
    buffer.writeln('        AllowOverride All');
    buffer.writeln('        Require all granted');
    buffer.writeln('    </Directory>');
    buffer.writeln('    Alias /__phpmyadmin "$pmaDir"');
    buffer.writeln('    <Directory "$pmaDir">');
    buffer.writeln('        Options Indexes FollowSymLinks');
    buffer.writeln('        AllowOverride All');
    buffer.writeln('        Require all granted');
    buffer.writeln('    </Directory>');
    buffer.writeln('    <FilesMatch \\.php\$>');
    buffer.writeln('        SetHandler "proxy:fcgi://127.0.0.1:9000"');
    buffer.writeln('    </FilesMatch>');
    buffer.writeln('</VirtualHost>\n');

    final ssl = SslService.instance;
    await ssl.ensureCertificate(sites: sites);
    final hasSsl = ssl.hasCertificate;
    final sslCert = _toForwardSlash(ssl.certPath);
    final sslKey = _toForwardSlash(ssl.keyPath);

    for (var site in sites) {
      if (!site.isEnabled) continue;
      final cleanDomain = site.domain.trim().toLowerCase();
      if (cleanDomain.isEmpty) continue;

      if (site.type == 'proxy') {
        buffer.writeln('# VirtualHost: ${site.domain} (Proxy)');
        buffer.writeln('<VirtualHost *:80>');
        buffer.writeln('    ServerName ${site.domain}');
        buffer.writeln('    ProxyPreserveHost On');
        buffer.writeln('    ProxyPass / http://127.0.0.1:${site.proxyPort}/');
        buffer.writeln('    ProxyPassReverse / http://127.0.0.1:${site.proxyPort}/');
        buffer.writeln('</VirtualHost>\n');

        if (hasSsl) {
          buffer.writeln('<VirtualHost *:443>');
          buffer.writeln('    ServerName ${site.domain}');
          buffer.writeln('    SSLEngine on');
          buffer.writeln('    SSLCertificateFile "$sslCert"');
          buffer.writeln('    SSLCertificateKeyFile "$sslKey"');
          buffer.writeln('    ProxyPreserveHost On');
          buffer.writeln('    ProxyPass / http://127.0.0.1:${site.proxyPort}/');
          buffer.writeln('    ProxyPassReverse / http://127.0.0.1:${site.proxyPort}/');
          buffer.writeln('</VirtualHost>\n');
        }
      } else {
        final docRoot = _getEffectiveDocRoot(site.rootPath);
        final fcgiPort = getFastCgiPort(site.phpVersion);
        buffer.writeln('# VirtualHost: ${site.domain} (PHP ${site.phpVersion} / Static)');
        buffer.writeln('<VirtualHost *:80>');
        buffer.writeln('    ServerName ${site.domain}');
        buffer.writeln('    DocumentRoot "$docRoot"');
        buffer.writeln('    <Directory "$docRoot">');
        buffer.writeln('        Options Indexes FollowSymLinks MultiViews');
        buffer.writeln('        AllowOverride All');
        buffer.writeln('        Require all granted');
        buffer.writeln('    </Directory>');
        buffer.writeln('    <FilesMatch \\.php\$>');
        buffer.writeln('        SetHandler "proxy:fcgi://127.0.0.1:$fcgiPort"');
        buffer.writeln('    </FilesMatch>');
        buffer.writeln('</VirtualHost>\n');

        if (hasSsl) {
          buffer.writeln('<VirtualHost *:443>');
          buffer.writeln('    ServerName ${site.domain}');
          buffer.writeln('    DocumentRoot "$docRoot"');
          buffer.writeln('    SSLEngine on');
          buffer.writeln('    SSLCertificateFile "$sslCert"');
          buffer.writeln('    SSLCertificateKeyFile "$sslKey"');
          buffer.writeln('    <Directory "$docRoot">');
          buffer.writeln('        Options Indexes FollowSymLinks MultiViews');
          buffer.writeln('        AllowOverride All');
          buffer.writeln('        Require all granted');
          buffer.writeln('    </Directory>');
          buffer.writeln('    <FilesMatch \\.php\$>');
          buffer.writeln('        SetHandler "proxy:fcgi://127.0.0.1:$fcgiPort"');
          buffer.writeln('    </FilesMatch>');
          buffer.writeln('</VirtualHost>\n');
        }
      }
    }

    File(config.apacheVhostsFile).writeAsStringSync(buffer.toString());
  }

  void _ensureNginxHelperFiles(String confDir) {
    final mimeFile = File(p.join(confDir, 'mime.types'));
    if (!mimeFile.existsSync()) {
      mimeFile.writeAsStringSync('''
types {
    text/html                             html htm shtml;
    text/css                              css;
    text/xml                              xml;
    image/gif                             gif;
    image/jpeg                            jpeg jpg;
    application/javascript                js;
    application/json                      json;
    application/xml                       rss;
    image/png                             png;
    image/svg+xml                         svg svgz;
    image/webp                            webp;
    image/x-icon                          ico;
    font/woff                             woff;
    font/woff2                            woff2;
    application/font-woff                 woff;
    application/font-woff2                woff2;
    application/vnd.ms-fontobject         eot;
    application/x-font-ttf                ttf;
    video/mp4                             mp4;
    video/webm                            webm;
    audio/mpeg                            mp3;
    application/pdf                       pdf;
    application/zip                       zip;
}
''');
    }

    final fastcgiFile = File(p.join(confDir, 'fastcgi_params'));
    if (!fastcgiFile.existsSync()) {
      fastcgiFile.writeAsStringSync('''
fastcgi_param  SCRIPT_FILENAME    \$document_root\$fastcgi_script_name;
fastcgi_param  QUERY_STRING       \$query_string;
fastcgi_param  REQUEST_METHOD     \$request_method;
fastcgi_param  CONTENT_TYPE       \$content_type;
fastcgi_param  CONTENT_LENGTH     \$content_length;

fastcgi_param  SCRIPT_NAME        \$fastcgi_script_name;
fastcgi_param  REQUEST_URI        \$request_uri;
fastcgi_param  DOCUMENT_URI       \$document_uri;
fastcgi_param  DOCUMENT_ROOT      \$document_root;
fastcgi_param  SERVER_PROTOCOL    \$server_protocol;
fastcgi_param  REQUEST_SCHEME     \$scheme;
fastcgi_param  HTTPS              \$https if_not_empty;

fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
fastcgi_param  SERVER_SOFTWARE    nginx/\$nginx_version;

fastcgi_param  REMOTE_ADDR        \$remote_addr;
fastcgi_param  REMOTE_PORT        \$remote_port;
fastcgi_param  SERVER_ADDR        \$server_addr;
fastcgi_param  SERVER_PORT        \$server_port;
fastcgi_param  SERVER_NAME        \$server_name;

# PHP only, required if PHP was built with --enable-force-cgi-redirect
fastcgi_param  REDIRECT_STATUS    200;
''');
    }
  }
}
